x-service-template: &service-template
  image: go-debug
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    SRC_DIR: ${SRC_DIR}
    MAIN_FILE_PATH: ${MAIN_FILE_PATH}
  depends_on:
    - postgres
  volumes:
    - type: bind
      source: ${SRC_DIR}
      target: ${SRC_DIR}
    - type: bind
      source: ./config.yaml
      target: /config.yaml
    - type: volume
      source: ciam-next-dev-cache
      target: /root/.cache
    - type: volume
      source: ciam-next-mod-cache
      target: /go/pkg/mod
  working_dir: ${SRC_DIR}
  restart: no

services:
  postgres:
    image: postgres:17.0
    environment:
      - "POSTGRES_USER=ciam"
      - "POSTGRES_PASSWORD=ciam"
      - "POSTGRES_DB=ciam"
    ports:
      - "5788:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciam"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - type: volume
        source: ciam-next-postgres
        target: /var/lib/postgresql/data

  server:
    <<: *service-template
    depends_on:
      - migrator
    command:
      - serve
      - --config=/config.yaml
    ports:
      - "${SERVER_DEBUG_PORT}:40000"
      - "8787:8787"

  migrator:
    <<: *service-template
    command:
      - migrate
      - --config=/config.yaml
    ports:
      - "${MIGRATOR_DEBUG_PORT}:40000"

volumes:
  ciam-next-dev-cache:
  ciam-next-mod-cache:
  ciam-next-postgres: